# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c279f6c8439863bb25cba1a6c63ca02c49cde1a6129d83bbc8bb12858005d8c37daa2394d59e158753c82b76090092c9bd3e264b29622cea6e92b87db65938aa

test:
  secret_key_base: dfd879b36ee9cbf9c7ead7d2f56ead950e61adfe359fcdd5032f1a27217ecdd0bf3e334f8ad91e58efcc46a13260a31773d32f12b8de0c82975a60bc2959187c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
